[package]
name = "ksmapcli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
ksmap = { path = "../ksmap" }
libks = { path = "../../libks/libks" }
